# Generated by Django 6.0.5 on 2026-05-12 22:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0002_categoriavisita_tipodocumento_empresa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_emissao', models.DateField(verbose_name='Data de Emissão')),
                ('data_vencimento', models.DateField(blank=True, null=True, verbose_name='Data de Vencimento')),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='documentos/', verbose_name='Arquivo Anexo')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='model.empresa', verbose_name='Empresa')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='documentos', to='model.tipodocumento', verbose_name='Tipo de Documento')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
            },
        ),
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_agendamento', models.DateTimeField(verbose_name='Data e Hora do Agendamento')),
                ('data_realizacao', models.DateTimeField(blank=True, null=True, verbose_name='Data e Hora da Realização')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('realizada', models.BooleanField(default=False, verbose_name='Visita Realizada')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='visitas', to='model.categoriavisita', verbose_name='Categoria da Visita')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitas', to='model.empresa', verbose_name='Empresa')),
                ('fiscal', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='visitas_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Fiscal Responsável')),
            ],
            options={
                'verbose_name': 'Visita',
                'verbose_name_plural': 'Visitas',
            },
        ),
    ]
