# Generated by Django 6.0.5 on 2026-05-12 23:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0003_documento_visita'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome do Colaborador')),
                ('cpf', models.CharField(max_length=11, unique=True, verbose_name='CPF')),
                ('data_entrada', models.DateField(verbose_name='Data de Entrada')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colaboradores', to='model.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Colaborador',
                'verbose_name_plural': 'Colaboradores',
            },
        ),
        migrations.CreateModel(
            name='LogAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_registro', models.IntegerField(blank=True, null=True, verbose_name='ID do Registro Afetado')),
                ('tipo', models.CharField(max_length=50, verbose_name='Tipo de Ação')),
                ('data_hora', models.DateTimeField(auto_now_add=True, verbose_name='Data e Hora')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Log de Auditoria',
                'verbose_name_plural': 'Logs de Auditoria',
            },
        ),
        migrations.CreateModel(
            name='NecessidadeDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='necessidades_documento', to='model.empresa', verbose_name='Empresa')),
                ('tipo_documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='necessidades_documento', to='model.tipodocumento', verbose_name='Tipo de Documento')),
            ],
            options={
                'verbose_name': 'Necessidade de Documento',
                'verbose_name_plural': 'Necessidades de Documentos',
                'unique_together': {('empresa', 'tipo_documento')},
            },
        ),
    ]
