# Generated by Django 6.0.5 on 2026-05-18 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0004_colaborador_logauditoria_necessidadedocumento'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='data_vencimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Vencimento (1 Ano)'),
        ),
        migrations.AddField(
            model_name='visita',
            name='responsavel_tecnico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='model.responsaveltecnico', verbose_name='Responsável Técnico (Época)'),
        ),
    ]
