# Generated by Django 6.0.5 on 2026-05-20 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0005_colaborador_data_vencimento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='cnpj',
            field=models.CharField(max_length=20, unique=True, verbose_name='CNPJ'),
        ),
    ]
