# Generated by Django 6.0.5 on 2026-06-15 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0006_alter_empresa_cnpj'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='responsaveltecnico',
            name='empresa',
        ),
        migrations.AddField(
            model_name='documento',
            name='responsavel_tecnico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos', to='model.responsaveltecnico', verbose_name='Responsável Técnico'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='responsavel_tecnico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empresas', to='model.responsaveltecnico', verbose_name='Responsável Técnico'),
        ),
        migrations.AddField(
            model_name='tipodocumento',
            name='obrigatorio',
            field=models.BooleanField(default=False, verbose_name='Obrigatório'),
        ),
    ]
